---
title: "Untitled"
output: html_document
date: "2025-05-23"
---
## WORKING DIRECTORY 
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/home/duhyadi/Documents/paper1/diversity" )
```

## LIBRARIES
```{r}
library(doBy)
library(ggplot2)
library(dplyr)
```


## LOAD FILE: generated by vcftools 
```{r}
olotillo_clean <- read.csv("data_olotillo_mayo_2025.csv",header=T)
```

### Summary by scale, F ~ scale
```{r}
# Calcular estadísticas por grupo
Fscale <- summaryBy(F ~ scale, data = olotillo_clean, FUN = c(mean, median, sd, min, max))
```

```{r}
# Aplicar signif() solo a columnas numéricas (excluyendo la columna de grupo)
Fscale[ , -1] <- as.data.frame(lapply(Fscale[ , -1], function(x) signif(as.numeric(x), digits = 3)))
```

```{r}
olotillo_clean2 <- read.csv("data_olotillo_mayo_2025.csv",header=T)
```

```{r}
# Calcular estadísticas por grupo
Fscale2 <- summaryBy(F ~ scale, data = olotillo_clean, FUN = c(mean, median, sd, min, max))
```

```{r}
# Redondear a 3 cifras decimales (todas las columnas excepto la de agrupación)
Fscale2[ , -1] <- lapply(Fscale[ , -1], function(x) round(as.numeric(x), 3))
```

### Summary by scale, HETob ~ scale
```{r}
HETobscale <- summaryBy(HETob ~ scale, data=olotillo_clean, FUN=c(mean, median, sd, min, max))
```

```{r}
# Redondear a 3 cifras decimales (todas las columnas excepto la de agrupación)
HETobscale[ , -1] <- lapply(HETobscale[ , -1], function(x) round(as.numeric(x), 3))
```

### Summary by scale, HETex ~ scale
```{r}
HETexscale <- summaryBy(HETex ~ scale, data=olotillo_clean, FUN=c(mean, median, sd, min, max))
```


```{r}
# Redondear a 3 cifras decimales (todas las columnas excepto la de agrupación)
HETexscale[ , -1] <- lapply(HETexscale[ , -1], function(x) round(as.numeric(x), 3))
```

### Summary by scale, HOMex ~ scale
```{r}
HOMexscale <- summaryBy(HOMex ~ scale, data=olotillo_clean, FUN=c(mean, median, sd, min, max))
```

```{r}
# Redondear a 3 cifras decimales (todas las columnas excepto la de agrupación)
HOMexscale[ , -1] <- lapply(HOMexscale[ , -1], function(x) round(as.numeric(x), 3))
```

### Summary by scale, N_SITES ~ scale
```{r}
N_SITES <- summaryBy(N_SITES ~ scale, data=olotillo_clean, FUN=c(mean, median, sd, min, max))
```

```{r}
# Redondear a 3 cifras decimales (todas las columnas excepto la de agrupación)
N_SITES[ , -1] <- lapply(N_SITES[ , -1], function(x) round(as.numeric(x), 3))
```


