---
title: "Untitled"
output: html_document
date: "2025-08-12"
---

#WAKERHUST 12 DE AGOSTO DEL 2025, EN MI RECAMARA 7:52 AM 
# PARA RESPONDER A LOS REVISORES DE LA REVISTA 
# DATA DE LOS VALORES DE DIVERSIDAD GENETICA
# PARA OBTENER LOS VALORES POR POR ACCESION 

## WORKING DIRECTORY 
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/home/duhyadi/Documents/paper1_mayo2025/for_Alicia_2024/het_vcf/" )
```

## LIBRARIES
```{r}
library(doBy)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(readr)
library(stringr)
```

## LOAD FILE: generated by vcftools 
```{r}
df <- read.csv("data_diversity_ago2025")
```

```{r}
df_olotillo <- df[df$Race == "Olotillo",]
```


```{r}
df_sel <- df_olotillo %>% 
  select(accession_ID, F, HETob, HETex, HOMex)
  
```



# agrupar por accession_ID
```{r}
resumen <- df_sel %>% 
  group_by(accession_ID) %>% 
  summarise(
    F_mean        = round(mean (F, na.rm = TRUE),3),
    F_sd          = round(sd   (F, na.rm = TRUE),3),
    HETob_mean    = round(mean (HETob , na.rm = TRUE),3),
    HETob_sd      = round(sd   (HETob , na.rm = TRUE),3),
    HETex_mean    = round(mean (HETex , na.rm = TRUE),3),
    HETex_sd      = round(sd (HETex , na.rm = TRUE),3),
    HOMex_mean    = round(mean (HOMex , na.rm = TRUE),3),
    HOMex_sd      = round(sd (HOMex , na.rm = TRUE),3),
    n = n(),
    .groups = "drop"
  ) %>% 
  arrange(accession_ID)
```


```{r}
print(resumen, n = 50)
```

```{r}
tail(resumen)
```

```{r}
write.csv(resumen, "TableS3")
```

